version: '3'
services:
  backend:
    image: algocean/backend
    build:
      context: ./
      dockerfile: Dockerfile
      
    ports:
      - 8501-8506:8501-8506 # for the user streamlit app
      - 8265:8265
      - 8000:8000
      - 8888:8888
      - 8001:8001
      - 7865-7870:7865-7870
      
    volumes:
      - ./:/app
      - ./ocean.py/ocean_lib:/app/ocean.py/ocean_lib
      - ~/.ocean:/.ocean
      - ${OCEAN_ARTIFACTS_FOLDER}:/ocean-contracts/artifacts/

    networks:
      backend:
        ipv4_address: 172.15.0.9

    environment:
      OCEAN_ARTIFACTS_FOLDER: ${OCEAN_ARTIFACTS_FOLDER}
      ADDRESS_FILE: /ocean-contracts/artifacts/address.json
      OCEAN_NETWORK_URL: ${NETWORK_RPC_URL}
    env_file: 
      - .env
    command: bash -c "./scripts/startup.sh; tail -F anything"

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.15.0.1/24