name: algocean
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.0
  - pip:
    -  -r requirements.txt
    -  -e ./ocean.py
    -  -e ./ipfsspec
    -  -e ./ipfspy